# Generated by Django 4.2.10 on 2025-05-31 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(max_length=100, verbose_name="分析类型"),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="分析参数"),
                ),
                (
                    "result_summary",
                    models.TextField(blank=True, null=True, verbose_name="结果摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分析用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "分析记录",
                "verbose_name_plural": "分析记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
