"""
Django settings for cardata_platform project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&my7jod-l+7bp!@hti#k6z2c=#s26l^-t(+z9wkx^-=q(1inwi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '169.254.71.207', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    
    # 第三方应用
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "rest_framework",
    "django_filters",
    
    # 自定义应用
    "accounts",
    "dashboard",
    "data_analysis",
    "api",
    "crawler",
    "analysis_records",
    "analysis_results",
    "car_analysis",
    "car_api",
    "visualization",
    "analysis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cardata_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "cardata_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django-allauth配置
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # Django默认的认证后端
    'django.contrib.auth.backends.ModelBackend',
    # allauth特定的认证方法，例如邮箱登录
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauth设置
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # 使用用户名或邮箱登录
ACCOUNT_EMAIL_REQUIRED = False  # 注册时不要求邮箱
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 禁用邮箱验证
ACCOUNT_USERNAME_REQUIRED = True  # 要求用户名
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True  # 注册时输入两次密码
ACCOUNT_UNIQUE_EMAIL = True  # 邮箱唯一
LOGIN_REDIRECT_URL = '/'  # 登录后重定向到首页

# 邮箱配置（开发环境使用控制台输出）
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SimpleUI设置
SIMPLEUI_HOME_INFO = False  # 关闭首页信息
SIMPLEUI_ANALYSIS = False  # 关闭分析统计
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'  # 设置默认主题
SIMPLEUI_LOGO = 'images/logo.png'  # 设置LOGO

# REST Framework设置
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}
