# Generated by Django 4.2.10 on 2025-05-29 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("brand_popularity", "品牌流行度分析"),
                            ("brand_price_range", "品牌价格区间分析"),
                            ("brand_region_distribution", "品牌地区分布分析"),
                        ],
                        max_length=50,
                        verbose_name="分析类型",
                    ),
                ),
                ("result_data", models.JSONField(verbose_name="分析结果数据")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="分析摘要"),
                ),
            ],
            options={
                "verbose_name": "品牌分析结果",
                "verbose_name_plural": "品牌分析结果",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("brand_price", "品牌价格分析"),
                            ("region_price", "地区价格分析"),
                            ("year_price", "年份价格分析"),
                            ("mileage_price", "里程价格分析"),
                        ],
                        max_length=50,
                        verbose_name="分析类型",
                    ),
                ),
                ("result_data", models.JSONField(verbose_name="分析结果数据")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="分析摘要"),
                ),
            ],
            options={
                "verbose_name": "价格分析结果",
                "verbose_name_plural": "价格分析结果",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("region_car_count", "地区车辆数量分析"),
                            ("region_price_level", "地区价格水平分析"),
                            ("region_brand_preference", "地区品牌偏好分析"),
                        ],
                        max_length=50,
                        verbose_name="分析类型",
                    ),
                ),
                ("result_data", models.JSONField(verbose_name="分析结果数据")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="分析摘要"),
                ),
            ],
            options={
                "verbose_name": "地区分析结果",
                "verbose_name_plural": "地区分析结果",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleAttributeAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("fuel_type_analysis", "燃料类型分析"),
                            ("transmission_analysis", "变速箱类型分析"),
                            ("color_preference", "颜色偏好分析"),
                            ("engine_type_analysis", "发动机类型分析"),
                            ("mileage_distribution", "里程分布分析"),
                        ],
                        max_length=50,
                        verbose_name="分析类型",
                    ),
                ),
                ("result_data", models.JSONField(verbose_name="分析结果数据")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="分析摘要"),
                ),
            ],
            options={
                "verbose_name": "车辆属性分析结果",
                "verbose_name_plural": "车辆属性分析结果",
                "ordering": ["-analysis_date"],
            },
        ),
    ]
