# Generated by Django 4.2.10 on 2025-05-28 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="品牌名称"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/logos/",
                        verbose_name="品牌标志",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="品牌描述"),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="车型名称")),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("sedan", "轿车"),
                            ("suv", "SUV"),
                            ("mpv", "MPV"),
                            ("sports", "跑车"),
                            ("pickup", "皮卡"),
                        ],
                        max_length=20,
                        verbose_name="车身类型",
                    ),
                ),
                ("price_range", models.CharField(max_length=100, verbose_name="价格区间")),
                ("launch_date", models.DateField(verbose_name="上市日期")),
                ("is_listed", models.BooleanField(default=True, verbose_name="是否在售")),
                ("length", models.IntegerField(verbose_name="长度(mm)")),
                ("width", models.IntegerField(verbose_name="宽度(mm)")),
                ("height", models.IntegerField(verbose_name="高度(mm)")),
                ("wheelbase", models.IntegerField(verbose_name="轴距(mm)")),
                ("engine", models.CharField(max_length=100, verbose_name="发动机")),
                ("transmission", models.CharField(max_length=100, verbose_name="变速箱")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.brand",
                        verbose_name="品牌",
                    ),
                ),
            ],
            options={
                "verbose_name": "车型",
                "verbose_name_plural": "车型",
                "ordering": ["brand", "name"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="综合评分"
                    ),
                ),
                (
                    "exterior_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="外观评分"
                    ),
                ),
                (
                    "interior_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="内饰评分"
                    ),
                ),
                (
                    "configuration_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="配置评分"
                    ),
                ),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="性能评分"
                    ),
                ),
                (
                    "comfort_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="舒适度评分"
                    ),
                ),
                (
                    "cost_performance_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="性价比评分"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="评价时间"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.carmodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户评分",
                "verbose_name_plural": "用户评分",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(verbose_name="月份")),
                ("sales_volume", models.IntegerField(verbose_name="销量")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.carmodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "销量数据",
                "verbose_name_plural": "销量数据",
                "ordering": ["-month"],
                "unique_together": {("car", "month")},
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.carmodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格历史",
                "verbose_name_plural": "价格历史",
                "ordering": ["-date"],
                "unique_together": {("car", "date")},
            },
        ),
    ]
