# Generated by Django 4.2.10 on 2025-05-28 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="地址"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="个人简介"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "高中及以下"),
                    ("college", "大专"),
                    ("bachelor", "本科"),
                    ("master", "硕士"),
                    ("phd", "博士"),
                ],
                max_length=20,
                null=True,
                verbose_name="学历",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女"), ("other", "其他")],
                max_length=10,
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="兴趣爱好"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="职业"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_github",
            field=models.URLField(blank=True, null=True, verbose_name="GitHub"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_wechat",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="微信"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_weibo",
            field=models.URLField(blank=True, null=True, verbose_name="微博"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="个人网站"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="company",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="公司"
            ),
        ),
    ]
