# Generated by Django 5.2 on 2025-05-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品牌名称")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/",
                        verbose_name="品牌logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "汽车品牌",
                "verbose_name_plural": "汽车品牌",
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="车型名称")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_models",
                        to="crawler.brand",
                        verbose_name="所属品牌",
                    ),
                ),
            ],
            options={
                "verbose_name": "汽车车型",
                "verbose_name_plural": "汽车车型",
            },
        ),
        migrations.CreateModel(
            name="UsedCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格(万)"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "mileage",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="里程(万公里)"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="地区")),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="颜色"
                    ),
                ),
                (
                    "displacement",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="排量"
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="变速箱"
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="燃油类型"
                    ),
                ),
                ("detail_url", models.URLField(verbose_name="详情链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_cars",
                        to="crawler.carmodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "二手车数据",
                "verbose_name_plural": "二手车数据",
                "ordering": ["-created_at"],
            },
        ),
    ]
