# Generated by Django 4.2.10 on 2025-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usedcar",
            name="year",
        ),
        migrations.AddField(
            model_name="usedcar",
            name="accident_check",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="出险查询"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="additional_info",
            field=models.TextField(blank=True, null=True, verbose_name="更多"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="cltc_range",
            field=models.IntegerField(blank=True, null=True, verbose_name="CLTC纯电续航里程"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="config_highlights",
            field=models.TextField(blank=True, null=True, verbose_name="配置亮点"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="detail",
            field=models.TextField(blank=True, null=True, verbose_name="车辆详情"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="drive_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="驱动方式"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="emission_standard",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="排放标准"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="engine",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="发动机"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="fuel_grade",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="燃油标号"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="inspection_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="年检到期"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="insurance_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="保险到期"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="maintenance",
            field=models.TextField(blank=True, null=True, verbose_name="维修保养"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="nedc_range",
            field=models.IntegerField(blank=True, null=True, verbose_name="NEDC纯电续航里程"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="registration_date",
            field=models.DateField(blank=True, null=True, verbose_name="上牌时间"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="standard_capacity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="标准容量"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="standard_fast_charging",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="标准快充"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="standard_slow_charging",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="标准慢充"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="transfer_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="过户次数"),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="vehicle_class",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="车辆级别"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="warranty_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="质保到期"),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="车身颜色"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="fuel_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="燃料类型"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="location",
            field=models.CharField(max_length=100, verbose_name="所在地"),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="mileage",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="表显里程"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="title",
            field=models.CharField(max_length=200, verbose_name="车辆名称"),
        ),
    ]
