# Generated by Django 4.2.10 on 2025-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_remove_usedcar_year_usedcar_accident_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usedcar",
            name="mileage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="表显里程",
            ),
        ),
    ]
