# Generated by Django 4.2.10 on 2025-05-29 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_usedcar_mileage"),
    ]

    operations = []
