# Generated by Django 4.2.10 on 2025-05-30 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crawler", "0004_auto_20250529_2201"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usedcar",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="config_highlights",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="warranty_due_date",
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("price_by_brand", "品牌价格分析"),
                            ("price_by_region", "地区价格分析"),
                            ("price_by_year", "年份价格分析"),
                            ("price_by_mileage", "里程价格分析"),
                            ("count_by_brand", "品牌数量分析"),
                            ("count_by_region", "地区数量分析"),
                            ("count_by_fuel", "燃料类型分析"),
                            ("count_by_transmission", "变速箱类型分析"),
                            ("count_by_color", "车身颜色分析"),
                        ],
                        max_length=50,
                        verbose_name="分析类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="分析标题")),
                ("filters", models.JSONField(default=dict, verbose_name="筛选条件")),
                ("result_data", models.JSONField(verbose_name="分析结果数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "分析结果历史",
                "verbose_name_plural": "分析结果历史",
                "ordering": ["-created_at"],
            },
        ),
    ]
