# Generated by Django 4.2.10 on 2025-05-31 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crawler", "0005_remove_usedcar_additional_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "target_count",
                    models.IntegerField(default=100, verbose_name="目标爬取数量"),
                ),
                ("actual_count", models.IntegerField(default=0, verbose_name="实际爬取数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("stopped", "已停止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                ("crawled_data", models.JSONField(default=list, verbose_name="爬取的数据")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬虫任务",
                "verbose_name_plural": "爬虫任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
            },
        ),
        migrations.AlterModelOptions(
            name="carmodel",
            options={
                "ordering": ["brand__name", "name"],
                "verbose_name": "车型",
                "verbose_name_plural": "车型",
            },
        ),
        migrations.AlterModelOptions(
            name="usedcar",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "二手车",
                "verbose_name_plural": "二手车",
            },
        ),
        migrations.RemoveField(
            model_name="brand",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="cltc_range",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="color",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="detail",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="engine",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="fuel_grade",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="inspection_due_date",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="insurance_due_date",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="maintenance",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="nedc_range",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="publish_date",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="registration_date",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="standard_capacity",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="standard_fast_charging",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="standard_slow_charging",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="transmission",
        ),
        migrations.RemoveField(
            model_name="usedcar",
            name="vehicle_class",
        ),
        migrations.AddField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="annual_inspection",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="年检到期"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="first_registration",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="首次上牌"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="gearbox",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="变速箱"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="insurance_expiry",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="保险到期"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="usage_nature",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="使用性质"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="品牌名称"),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crawler.brand",
                verbose_name="品牌",
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="name",
            field=models.CharField(max_length=200, verbose_name="车型名称"),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="accident_check",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="事故排查"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="car_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crawler.carmodel",
                verbose_name="车型",
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="detail_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="详情链接"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="displacement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="排量"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="drive_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="驱动方式"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="emission_standard",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="排放标准"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="fuel_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="燃料类型"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所在地"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="mileage",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="里程"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="价格(万元)",
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="title",
            field=models.CharField(max_length=500, verbose_name="车辆标题"),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="transfer_count",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="过户次数"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carmodel",
            unique_together={("brand", "name")},
        ),
        migrations.DeleteModel(
            name="AnalysisResult",
        ),
    ]
