# Generated by Django 4.2.10 on 2025-05-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0006_crawlertask_alter_brand_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlertask",
            name="delay_seconds",
            field=models.FloatField(default=2.0, verbose_name="爬取间隔(秒)"),
        ),
        migrations.AddField(
            model_name="crawlertask",
            name="end_page",
            field=models.IntegerField(blank=True, null=True, verbose_name="终止页码"),
        ),
        migrations.AddField(
            model_name="crawlertask",
            name="search_keyword",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="搜索关键词"
            ),
        ),
        migrations.AddField(
            model_name="crawlertask",
            name="start_page",
            field=models.IntegerField(default=1, verbose_name="起始页码"),
        ),
    ]
