# Generated by Django 4.2.10 on 2025-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0007_crawlertask_delay_seconds_crawlertask_end_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usedcar",
            name="mileage_text",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="里程原始文本"
            ),
        ),
        migrations.AddField(
            model_name="usedcar",
            name="registration_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="上牌日期"
            ),
        ),
        migrations.AlterField(
            model_name="usedcar",
            name="mileage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=10,
                null=True,
                verbose_name="里程(万公里)",
            ),
        ),
    ]
