# Generated by Django 4.2.10 on 2025-05-28 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("segment", "细分市场分析"),
                            ("competition", "竞争态势分析"),
                            ("trend", "市场趋势分析"),
                        ],
                        max_length=20,
                        verbose_name="分析类型",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                (
                    "target_segment",
                    models.CharField(max_length=100, verbose_name="目标细分市场"),
                ),
                ("analysis_data", models.JSONField(verbose_name="分析数据")),
                ("insights", models.TextField(verbose_name="分析洞察")),
            ],
            options={
                "verbose_name": "市场分析",
                "verbose_name_plural": "市场分析",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                ("prediction_data", models.JSONField(verbose_name="预测数据")),
                ("accuracy", models.FloatField(verbose_name="预测准确度")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.carmodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "销量分析",
                "verbose_name_plural": "销量分析",
                "ordering": ["-analysis_date"],
                "unique_together": {("car", "analysis_date")},
            },
        ),
        migrations.CreateModel(
            name="PriceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="分析日期"
                    ),
                ),
                ("trend_data", models.JSONField(verbose_name="趋势数据")),
                ("prediction_data", models.JSONField(verbose_name="预测数据")),
                ("confidence_level", models.FloatField(verbose_name="置信度")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.carmodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格分析",
                "verbose_name_plural": "价格分析",
                "ordering": ["-analysis_date"],
                "unique_together": {("car", "analysis_date")},
            },
        ),
    ]
