# Generated by Django 4.2.10 on 2025-05-28 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="图表标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="图表描述"),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "折线图"),
                            ("bar", "柱状图"),
                            ("pie", "饼图"),
                            ("scatter", "散点图"),
                            ("heatmap", "热力图"),
                            ("radar", "雷达图"),
                        ],
                        max_length=20,
                        verbose_name="图表类型",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("sales", "销量数据"),
                            ("price", "价格数据"),
                            ("rating", "评分数据"),
                            ("comment", "评论数据"),
                        ],
                        max_length=20,
                        verbose_name="数据类型",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="图表配置")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "图表",
                "verbose_name_plural": "图表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="仪表盘标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="仪表盘描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
            ],
            options={
                "verbose_name": "仪表盘",
                "verbose_name_plural": "仪表盘",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.IntegerField(default=0, verbose_name="X轴位置")),
                ("position_y", models.IntegerField(default=0, verbose_name="Y轴位置")),
                ("width", models.IntegerField(default=6, verbose_name="宽度")),
                ("height", models.IntegerField(default=4, verbose_name="高度")),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualization.chart",
                        verbose_name="图表",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visualization.dashboard",
                        verbose_name="所属仪表盘",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪表盘图表",
                "verbose_name_plural": "仪表盘图表",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.AddField(
            model_name="dashboard",
            name="charts",
            field=models.ManyToManyField(
                through="visualization.DashboardChart",
                to="visualization.chart",
                verbose_name="包含的图表",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.CreateModel(
            name="ChartFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50, verbose_name="字段名")),
                ("operator", models.CharField(max_length=20, verbose_name="操作符")),
                ("value", models.CharField(max_length=200, verbose_name="筛选值")),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="visualization.chart",
                        verbose_name="所属图表",
                    ),
                ),
            ],
            options={
                "verbose_name": "图表筛选",
                "verbose_name_plural": "图表筛选",
            },
        ),
    ]
